# ===================================
#  Relation Behavior Config
# ===================================

fields:
    label: Fields
    view:
        list: $/novelus/forms/models/field/columns.yaml
        toolbarButtons: create|delete
        defaultSort:
            column: order
            direction: asc

    manage:
        form: $/novelus/forms/models/field/fields.yaml
