plugin:
    name: 'novelus.forms::lang.plugin.name'
    description: 'novelus.forms::lang.plugin.description'
    author: Novelus
    icon: oc-icon-align-justify
    homepage: 'https://novelus.eu'
navigation:
    main-menu-item:
        label: Forms
        url: novelus/forms/forms
        icon: icon-align-justify
        sideMenu:
            side-menu-item:
                label: Forms
                url: novelus/forms/forms
                icon: icon-list-alt
            side-menu-item2:
                label: Submissions
                url: novelus/forms/submissions
                icon: icon-list
